### ISSUE TITLE
API rewrite for `conditional_join`

### ISSUE THREAD

**Issue by samukweku** [pyjanitor-devs/pyjanitor#1234]
In a bid to move from the string API for conditional join --> `(left, right, '>')`, I am thinking of implementing an IEJoin class - it does nothing - it is just an expression of what will be evaluated. 

At the moment, I'm thinking of some thing in this form:

```py
df1.conditional_join(df2, IEJoin('A').less_than('B'), IEJoin('A').greater_than('C'), ...)
```

This way we avoid the string representation of the comparators `>`, `<`, `!=` .... Also there is not evaluation of the IEJoin; it just holds the column labels and comparator, we then pass that to the `conditional_join` function to execute.

Just a thought, it might very well be that the current API is ok and folks do not have an issue with it. Would love to get feedback , if any.

**Comment by ericmjl** [comment]
Interesting proposal, @samukweku! 

I agree with your general sentiment that the current API could be improved. My main thoughts are for human readability. Usually, I would read the following API as "col 1 less than col 2", or more generally (col1, operator, col2). We currently have `operator` and `col2` swapped, if I remember correctly. Switching to anything that reads more naturally is probably preferable. 

Question, where is `IEJoin` inspired from? It's something I've not seen before. I am a little bit concerned about introducing a new object into the library, as it creates more overhead for users. What if we instead used strings (e.g. "col1 < col2") and wrote a parser for that syntax?

**Comment by ericmjl** [comment]
Update from me, @samukweku. I started studying your other PRs and I think I'm getting where the IECols object is coming from. Please disregard my last comment if you think IECols is better from a usability + flexibility perspective!

**Comment by thatlittleboy** [comment]
Could we maybe verbalize here what the benefit is in making this move? Naively, `IEJoin('A').less_than('B')` is more lengthy to write and arguably slightly more complicated to understand than `("A", "B", "<")` as someone new to the API won't know what `IEJoin` does. For a library like `pyjanitor` whose main focus is on sugary syntax/method-chaining, I would probably lean more towards keeping the complexity within rather than exposing them in the API. Downside being that it's now harder to maintain (?).

> This way we avoid the string representation of the comparators >, <, != ....

Curious: What's the concern here?

---

From a usability perspective, I'm generally more in favour of the pyspark/polars/sql-like syntax, so either `"A < B"` as a single string as per Eric's initial suggestion, or `col("A") < col("B")` where we overload the `__lt__` etc. magic methods on a Column object.

And this way, we could hook into Python's built in support for `col("A") < col("B") < col("C")` also, perhaps?

**Comment by samukweku** [comment]
thanks for the feedback so far ... 

perf wise conditional_join is in a good place, i just wasnt sure if the current api was good enuf. Seems it is in a good place.

I do however like the idea of `col("A") < col("B") < col("C")` as suggested by @thatlittleboy ... looks nice and I can even use the `col` object in a number of other functions ... thanks @thatlittleboy 

still open to more ideas, if any - at the moment I've got two options, leave things as is, or just add the `col` concept as well, without deprecating the tuple syntax yet.

**Comment by samukweku** [comment]
Closing this ... Thanks for the ideas, the simplicity of the existing API with the tuple approach is ok and no complaints so far 🤞
