### ISSUE TITLE
multipledispatch added as dev dependency but needed in production

### ISSUE THREAD

**Issue by adamzev** [pyjanitor-devs/pyjanitor#804]
# Brief Description

In this commit (https://github.com/ericmjl/pyjanitor/commit/331f4a858055079d1504c36c543e72c6c19bca6b) the library is now used in a function but it was just added to dev dependencies. I think this may have happened before. It fails for my app's CICD which imports PyJanitor. Does PyJanitor have a CICD process that doesn't import dev dependencies?

# Error Messages

```
/usr/local/lib/python3.8/site-packages/janitor/functions.py:28: in <module>
    from multipledispatch import dispatch
E   ModuleNotFoundError: No module named 'multipledispatch'
```

**Comment by ericmjl** [comment]
@adamzev thank you for the catch! matt rocklin's multipledispatch is now a full-fledged dependency because it enables us to write some of the code a bit more cleanly. It being absent is an oversight on my part; we were focused on other pieces of automation recently that I forgot to add that in. Appreciate the prompt response, give me a few hours max to get the package updated and kickstart the bots.
