### ISSUE TITLE
Request: highlight pyjanitor on Interrogate's documentation

### ISSUE THREAD

**Issue by econchick** [pyjanitor-devs/pyjanitor#815]
Hey there! - I really appreciate that pyjanitor uses [interrogate](https://github.com/econchick/interrogate)! It's super flattering!

I'm wondering, may I mention that pyjanitor uses interrogate on our [docs site](https://interrogate.readthedocs.io)? Something just as simple as a section of "Projects that use Interrogate" with the name and link under it. If you'd like, I can include the pyjanitor logo, and/or even a quote about why it's used 😅

I totally understand if you'd prefer not to! I won't put anything up until I hear from you.

Thanks!

**Comment by ericmjl** [comment]
@econchick interrogate is awesome! It's caught me multiple times when I try to commit code that doesn't have any docstrings. I find myself thinking, "Might as well write something good here, since interrogate is making me write one." And then something decent gets committed. Wonderful work building out interrogate! Please do feel free to highlight it. :smile:

**Comment by econchick** [comment]
Thank you! Finally got it [up there](https://interrogate.readthedocs.io/en/latest/#users-of-interrogate). Cheers! 🎉
