### ISSUE TITLE
[ENH] Add a make_clean_names function for cleaning dataframe values

### ISSUE THREAD

**Issue by alfredojoseneto** [pyjanitor-devs/pyjanitor#995]
# Brief Description

Hi! I would like to propose the creation of a function like "**janitor::make_clean_names()**". This function exists on janitor in R.
It's an amazing function because we can normalize any text in a apply and lambda function.
Thanks in advance.

# Example

Below there is an example of the function application in a R environment.

```r
> janitor::make_clean_names("Abçdê fgí j")
[1] "abcde_fgi_j"

> janitor::make_clean_names("(--Abc\\dÊ fg#$klmnö)")
[1] "abc_d_e_fg_number_klmno"
```

**Comment by samukweku** [comment]
[clean_names](https://pyjanitor-devs.github.io/pyjanitor/api/functions/#janitor.functions.clean_names.clean_names) exists already

**Comment by alfredojoseneto** [comment]
> [clean_names](https://pyjanitor-devs.github.io/pyjanitor/api/functions/#janitor.functions.clean_names.clean_names) exists already

**Comment by alfredojoseneto** [comment]
I tried clean_names, but its apply only over column names. I'm looking for "make_clean_names()" because this function apply over any text in the rows.

**Comment by ericmjl** [comment]
This is a neat suggestion, @alfredojoseneto! Thanks for suggesting it. 

I think having the functionality ported over is a great idea, and I'm in favour of it.

At the same time, I'd like to consider the naming of the function itself a bit more carefully. Usually, I'd prefer that we just repeat the R function name in `pyjanitor`, but in this case I'm also seeing the potential for namespace confusion, and therefore [pytorch-like entropy](https://twitter.com/karpathy/status/1478564065660207105) in the codebase.

I see a few options. Here's me thinking them out aloud:

1. Modify the existing `clean_names` to provide an argument that declares whether it should be applied across: dataframe index, dataframe column, or dataframe values (hence corresponding to the natural anatomy of a pandas Dataframe)
2. Provide a new text cleaning function, named `clean_text`, that can be called as a dataframe class method. It can use the same underlying functions as `clean_names`, but it strictly applies to just the dataframe values.

Modifying `clean_names`' behaviour seems okay to me, though now we're generalizing it to `clean_text` rather than it being merely a `clean_name` (i.e. for column names or row names), where `name` covers a stricter subset of items than `text`. Hence the idea of providing `clean_text` as the function name instead of `clean_names`. I figure that as long as the documentation of `clean_text` is done right, and that it is placed proximally close to `clean_names` in the codebase, then given their similarity in functionality, long-term maintenance should be okay.

Having said all of that, what are your thoughts, @alfredojoseneto and @samukweku? @alfredojoseneto, we green-light the idea on the dev team, would you be open to contributing that functionality to the pyjanitor codebase? I'd be happy to guide you through it; there may be a few rounds of back-and-forth to shape it right, but I think that'd be an awesome contribution and I'd love for you to be able to partake in the development process, if that's something you desire!
